package no.hvl.dat250.jpa.assignment.message;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NonNull;

@Data
public class PollAnalytic {

    @NonNull
    private String question;

    @NonNull
    private String theme;

    @NonNull
    private String owner;

    @NonNull
    private Integer yesVotes;

    @NonNull
    private Integer noVotes;

    @NonNull
    private Integer deviceVotes;

    @NonNull
    private Integer userVotes;

    @NonNull
    private Integer anonymousVotes;
}
