package com.example.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "PollAnalytic")
public class PollAnalytic {

    private String id;

    @NonNull
    private String question;

    @NonNull
    private String theme;

    @NonNull
    private String owner;

    @NonNull
    private Integer yesVotes;

    @NonNull
    private Integer noVotes;

    @NonNull
    private Integer deviceVotes;

    @NonNull
    private Integer userVotes;

    @NonNull
    private Integer anonymousVotes;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "Question")
    public String getQuestion() {
        return question;
    }

    @DynamoDBAttribute(attributeName = "Theme")
    public String getTheme() {
        return theme;
    }

    @DynamoDBAttribute(attributeName = "Owner")
    public String getOwner() {
        return owner;
    }

    @DynamoDBAttribute(attributeName = "YesVotes")
    public Integer getYesVotes() {
        return yesVotes;
    }

    @DynamoDBAttribute(attributeName = "NoVotes")
    public Integer getNoVotes() {
        return noVotes;
    }

    @DynamoDBAttribute(attributeName = "DeviceVotes")
    public Integer getDeviceVotes() {
        return deviceVotes;
    }

    @DynamoDBAttribute(attributeName = "UserVotes")
    public Integer getUserVotes() {
        return userVotes;
    }

    @DynamoDBAttribute(attributeName = "AnonymousVotes")
    public Integer getAnonymousVotes() {
        return anonymousVotes;
    }
}
